djangoapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djangoapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^templado/', include('templado.urls', namespace='templado')),
)

templado/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .views import ReportsListView, TemplatesListView, ReportFormView, DownloadReport, EditReportFormView, \
    TemplateFormView, SearchView, HelpView, UploadStaticView


urlpatterns = patterns('',
    url(r'^uploadstatic/$', UploadStaticView.as_view(), name='upload-static'),
    url(r'^create/$', TemplateFormView.as_view(), name='template-form'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^edit/(?P<template>\d+)/$', TemplateFormView.as_view(), name='edit-template-form'),
    url(r'^generate/(?P<template>\d+)/$', ReportFormView.as_view(), name='report-form'),
    url(r'^regenerate/(?P<report>\d+)/$', EditReportFormView.as_view(), name='edit-report-form'),
    url(r'^reports$', ReportsListView.as_view(), name='report-list'),
    url(r'^download/(?P<report>\d+)/$', DownloadReport.as_view(), name='download-report'),
    url(r'^help$', login_required(HelpView.as_view()), name='help'),
    url(r'^$', TemplatesListView.as_view(), name='template-list'),    
    url(
        r'^login/$',
        'django.contrib.auth.views.login',
        name='login',
        kwargs={'template_name': 'templado/login.html'}
    ),
    url(
        r'^logout/$',
        'django.contrib.auth.views.logout',
        name='logout',
        kwargs={'next_page': '/templado'}
    ),
    #url(r'^login/$', 'templado.views.login_user'),
    #url(r'^logout/$', 'django.contrib.auth.views.logout',  {'template_name': 'templado/logout.html'}),
)

templado/forms.py
from functools import wraps, partial
from django.core.validators import RegexValidator
from django.forms import Form, Field, CharField, TextInput, FileField
from collections import OrderedDict
from django.forms.formsets import formset_factory


class UploadStaticForm(Form):
    file = FileField()


class FormFromPattern(Form):
    def create_fields(self, pattern, *args, **kwargs):
        for key, value in pattern.iteritems():
            if key != 'STATIC_DIR':
                if isinstance(value['type'], unicode) or isinstance(value['type'], str):
                    self.fields[key] = CharField(required=True, label=value['caption'],
                                                 widget=TextInput(attrs={'placeholder': value['hint'],
                                                 }),
                                                 validators=[RegexValidator(value['check'], 'Wrong format')])
                elif isinstance(value['type'], list):  # formset
                    FormFromPatternFormSet = formset_factory(
                        wraps(FormFromPattern)(partial(FormFromPattern, pattern=value['type'][0], tags=False)),
                        extra=1, can_delete=True)
                    self.nested_formsets.append({'caption': value['caption'],
                                                 'name': key,
                                                 'formset': FormFromPatternFormSet(prefix=key, *args, **kwargs)})

    def __init__(self, pattern, tags, *args, **kwargs):
        super(FormFromPattern, self).__init__(*args, **kwargs)
        self.nested_formsets = []
        pattern = OrderedDict(sorted(pattern.items(), key=lambda i: i[1]['order']))
        self.create_fields(pattern, *args, **kwargs)
        if tags:
            self.fields['tags'] = CharField(required=False, label='Tags',
                                            widget=TextInput(attrs={'placeholder': 'Tags separated with comma',
                                            }), )

    def is_valid(self):
        form_is_valid = super(FormFromPattern, self).is_valid()
        for nested_formset in self.nested_formsets:
            if not nested_formset['formset'].is_valid():
                form_is_valid = False
        return form_is_valid

    def process(self):
        data = self.cleaned_data
        for nested_formset in self.nested_formsets:
            formset_data = [f.cleaned_data for f in nested_formset['formset'] if f.cleaned_data]
            data[nested_formset['name']] = formset_data
        return data


class SearchForm(Form):
    q = CharField(required=False, label='Search')

templado/views.py
import os
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from django.views.generic.list import ListView
import errno
from models import Report, ReportTemplate
from .modelforms import ReportTemplateForm
from templado.forms import UploadStaticForm
from templado.functions import save_static_file, get_uploaded_static_files
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import *
from django.shortcuts import render_to_response,redirect
from django.template import RequestContext

class ReportsListView(ListView):
    """
        Displays list of reports uses generic class based list view
        template_name = report_list.html
    """
    model = Report


class TemplatesListView(ListView):
    """
        Displays list of report templates uses generic class based list view
        template_name = reporttemplate_list.html
    """
    model = ReportTemplate


class BaseFormView(View):
    """
        Base form view interface is used in ReportFormView in EditReportFormView
    """
    template_name = 'templado/report_form.html'
    redirect_url = 'templado:report-list'

    def get_form(self, data=None, *args, **kwargs):
        """Takes form to display with proper data"""
        raise NotImplementedError

    def form_is_valid(self, data=None, *args, **kwargs):
        """actions after form validation"""
        raise NotImplementedError

    def get(self, request, *args, **kwargs):
        """displays proper form"""
        form = self.get_form(*args, **kwargs)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        """takes context from request and validates form"""
        form = self.get_form(request.POST, *args, **kwargs)
        if form.is_valid():
            self.form_is_valid(form.process(), *args, **kwargs)
            return redirect(self.redirect_url)
        return render(request, self.template_name, {'form': form})


class UploadStaticView(View):
    """
        View
    """
    template_name = 'templado/upload_static.html'
    redirect_url = 'templado:upload-static'

    def render(self, request, form):
        uploaded_files = get_uploaded_static_files()
        return render(request, self.template_name, {'form': form, 'files': uploaded_files})

    def get(self, request, *args, **kwargs):
        form = UploadStaticForm()
        return self.render(request, form)

    def post(self, request, *args, **kwargs):
        form = UploadStaticForm(request.POST, request.FILES)
        if form.is_valid():
            f = request.FILES['file']
            save_static_file(f)
            return redirect(self.redirect_url)
        return self.render(request, form)


class ReportFormView(BaseFormView):
    """
        Inherits methods get and post from BaseReportFormView
    """

    def get_template(self, **kwargs):
        return get_object_or_404(ReportTemplate, pk=kwargs['template'])

    def get_form(self, data=None, *args, **kwargs):
        """for given template generates report form"""
        return self.get_template(**kwargs).get_form(data)

    def form_is_valid(self, data=None, *args, **kwargs):
        """when form is valid, creates report from template with given data"""
        Report.objects.create_report(self.get_template(**kwargs), data, data.get('tags'))


class EditReportFormView(BaseFormView):
    """
        Inherits methods get and post from BaseReportView
    """

    def get_report(self, *args, **kwargs):
        return get_object_or_404(Report, pk=kwargs['report'])

    def get_form(self, data=None, *args, **kwargs):
        """for given report generates report form and fills it with its data"""
        return self.get_report(**kwargs).get_form_with_content(data)

    def form_is_valid(self, data=None, *args, **kwargs):
        """recreates report with new data"""
        Report.objects.recreate_report(self.get_report(**kwargs), data, data.get('tags'))


class DownloadReport(View):

    def get(self, request, *args, **kwargs):
        """returns pdf file with report"""
        report = get_object_or_404(Report, pk=kwargs['report'])
        filename = report.file.name.split('/')[-1]
        response = HttpResponse(report.file, content_type='application/pdf; charset=utf-8')
        response['Content-Disposition'] = 'inline; filename=%s' % filename
        return response


class TemplateFormView(View):
    """
        Form view for creating template objects
    """
    template_name = 'templado/reporttemplate_form.html'

    def get_template(self, **kwargs):
        return get_object_or_404(ReportTemplate, pk=kwargs.get('template'))

    def get(self, request, *args, **kwargs):
        if kwargs.get('template'):
            form = ReportTemplateForm(instance=self.get_template(**kwargs))
        else:
            form = ReportTemplateForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        if kwargs.get('template'):
            form = ReportTemplateForm(request.POST, request.FILES, instance=self.get_template(**kwargs))
        else:
            form = ReportTemplateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('templado:template-list')
        return render(request, self.template_name, {'form': form})


class HelpView(View):
    """
        Static help page
    """
    template_name='templado/help_site.html'
	
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


import re
from django.db.models import Q

def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    """ Splits the query string in invidual keywords, getting rid of unecessary spaces
        and grouping quoted words together.
        Example:

        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']

    """
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]


def get_query(query_string, search_fields):
    """ Returns a query, that is a combination of Q objects. That combination
        aims to search keywords within a model by testing the given search fields.
    """
    query = None  # Query to search for every search term
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None  # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query


class SearchView(View):
    """
        Simple search view for reports
    """
    template_name = 'templado/report_list.html'

    def get(self, request, *args, **kwargs):
        query_string = ''
        if 'q' in request.GET and request.GET['q'].strip():
            query_string = request.GET['q']
            entry_query = get_query(query_string, ['name', 'tags', 'auto_tags'])
            found_entries = Report.objects.filter(entry_query)
        else:
            found_entries = Report.objects.all()
        return render(request, self.template_name, {'object_list': found_entries,
                                                    'q': query_string, })

templado/templates/templado/base_site.html
{% extends 'templado/templado_site.html' %}

{% load staticfiles %}
{% load search_form %}
{% load active %}


{% block templado_title %}
    Templado
{% endblock %}

{% block templado_static %}
    <link rel="stylesheet" href="{% static 'templado/css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'templado/css/base.css' %}"/>
    <script src="{% static 'templado/js/jquery.js' %}"></script>
{% endblock %}

{% block templado_content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="search pull-right">
                    <form action="{% url 'templado:search' %}" method="get">
                        {% bootstrap_query_form request %}
                    </form>
                </div>
                <h4 class="templado-header">Templado</h4>
                <hr/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <ul class="nav nav-pills nav-stacked">
                    <li class="nav-header"></li>
                    <li class="{% is_active request 'templado:template-list' %}">
                        <a href="{% url 'templado:template-list' %}"><i
                                class="glyphicon glyphicon-list"></i> Templates</a>
                    </li>
                    <li class="{% is_active request 'templado:upload-static' %}">
                        <a href="{% url 'templado:upload-static' %}"><i
                                class="glyphicon glyphicon-picture"></i> Upload Static Files</a>
                    </li>
                    <li class="{% is_active request 'templado:template-form' %}">
                        <a href="{% url 'templado:template-form' %}"><i
                                class="glyphicon glyphicon-wrench"></i> Create Template</a>
                    </li>
                    <li class="{% is_active request 'templado:report-list' %}">
                        <a href="{% url 'templado:report-list' %}"><i
                                class="glyphicon glyphicon-list-alt"></i> Reports</a>
                    </li>
                    <li class="{% is_active request 'templado:help' %}">
                        <a href="{% url 'templado:help' %}"><i
                                class="glyphicon glyphicon-question-sign"></i> Help</a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-9">
                {% block app_content %}
                {% endblock %}
            </div>
        </div>

    </div>
{% endblock %}

templado/templates/templado/help_site.html
{% extends 'templado/base_site.html' %}
{% load bootstrap3 %}

{% block app_content %}
    App for creating reports from templates.
    <p>
        <strong>
            <a href="http://templado.readthedocs.org/en/latest/" target="blank">Manual and documentation</a>
        </strong>
    </p>
{% endblock %}

templado/templates/templado/login.html
{% extends "templado/base_site.html" %}

{% block app_content %}

  {% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
<form method="post" action="{% url 'templado:login' %}">
{% csrf_token %}
<table>
{{ form }}
</table>
<input type="submit" value="login" />
<input type="hidden" name="next" value="/" />
</form>
{% endblock %}

templado/templates/templado/logout.html
{% extends "templado/base_site.html" %}

{% block app_content %}

  <div>Wylogowales sie!</div>
  
{% endblock %}

templado/templates/templado/report_form.html
{% extends 'templado/base_site.html' %}
{% load bootstrap3 %}

{% block app_content %}
    {% include 'templado/report_form_partial.html' %}
{% endblock %}

templado/templates/templado/report_form_partial.html
{% load bootstrap3 %}
<form action="" method="post">
    {% csrf_token %}
    <div>
        {% bootstrap_form form %}
    </div>
    {% if form.nested_formsets %}
        {% for nested_formset in form.nested_formsets %}
            <script type="text/html" id="{{ nested_formset.name }}-template">
                <div class="{{ nested_formset.name }}-item formset">
                    <div class="row">
                        {% for field in nested_formset.formset.empty_form %}
                            <div class="col-sm-4">
                                {% bootstrap_field field %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </script>
            <div class="form-group">
                <p><strong>{{ nested_formset.caption }}:</strong></p>

                <div class="nested" id="{{ nested_formset.name }}-formset">
                    {{ nested_formset.formset.management_form }}
                    {% for nested_form in nested_formset.formset %}
                        <div class="{{ nested_formset.name }}-item formset">
                            <div class="row">
                                {% for field in nested_form %}
                                    <div class="col-sm-4">
                                        {% bootstrap_field field %}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}

                </div>
                <a href="#" class="btn btn-default btn-sm add-form"
                   id="{{ nested_formset.name }}">Add {{ nested_formset.name }} {% bootstrap_icon "plus" %}</a>

            </div>
        {% endfor %}
    {% endif %}
    <p>
        <input type="submit" class="btn btn-primary" value="Generate PDF"/>
    </p>
</form>

<script>
    $('.add-form').click(function (ev) {
        ev.preventDefault();
        var name = $(this).attr('id');
        var count = $('.' + name + '-item').length;
        var tmplMarkup = $('#' + name + '-template').html();
        tmplMarkup = tmplMarkup.replace(/__prefix__/g, count);
        var formset = $('#' + name + '-formset');
        formset.append(tmplMarkup);
        $('#id_' + name + '-TOTAL_FORMS').attr('value', count + 1);
    });
</script>

templado/templates/templado/report_list.html
{% extends 'templado/base_site.html' %}

{% block app_content %}
    {% if object_list %}
        {% for report in object_list|dictsortreversed:'finished' %}
            <div class="report-item">
                <div class="row">
                    <div class="col-sm-12">

                        <div class="buttons">
                            <div class="upper-btn">
                                <a class="btn btn-primary btn-sm btn-block"
                                   href="{% url 'templado:edit-report-form' report.id %}">Edit</a>
                            </div>
                            <div class="lower-btn">
                                <a class="btn btn-success btn-sm btn-block"

                                href="{% url 'templado:download-report' report.id %}">Download</a>
                            </div>
                        </div>

                        <div class="report-info">
                            <p class="report-header">
                                <small class="pull-right report-date">{{ report.finished }}</small>
                                {{ report.name }}
                            </p>
                            {{ report.all_tags }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="row text-content">
            <div class="col-sm-12">
                <p>No results</p>
            </div>
        </div>
    {% endif %}

{% endblock %}

templado/templates/templado/reporttemplate_form.html
{% extends 'templado/base_site.html' %}
{% load bootstrap3 %}

{% block app_content %}
    <form enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-primary" type="submit" value="Create!"/>
    </form>

{% endblock %}

templado/templates/templado/reporttemplate_list.html
{% extends 'templado/base_site.html' %}
{% load bootstrap3 %}

{% block app_content %}
    {% for template in object_list %}
        <div class="report-item">
            <div class="row">
                <div class="col-sm-12">

                    <div class="buttons">
                        <div class="upper-btn">
                            <a class="btn btn-primary btn-sm btn-block"
                               href="{% url 'templado:edit-template-form' template.id %}">Edit</a>
                        </div>
                        <div class="lower-btn">
                            <a class="btn btn-success btn-sm btn-block" href="{% url 'templado:report-form' template.id %}">Generate</a>
                        </div>
                    </div>

                    <div class="report-info">
                        <p class="report-header">
                            {{ template.title }}
                        </p>
                        {{ template.tags }}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templado/templates/templado/templado_site.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block templado_title %}
        {% endblock %}
    </title>
    {% block templado_static %}
    {% endblock %}
</head>
<body>
{% block templado_content %}
{% endblock %}
</body>
</html>

templado/templates/templado/upload_static.html
{% extends 'templado/base_site.html' %}
{% load bootstrap3 %}

{% block app_content %}
    <div>
        <strong>Uploaded files</strong>
        <ul>
            {% for file in files %}
                <li>{{ file }}</li>
            {% endfor %}
        </ul>
    </div>
    <form enctype="multipart/form-data" method="post" action="">
        {% csrf_token %}
        <div>
            {% bootstrap_form form %}
        </div>
        <p>
            <input type="submit" class="btn btn-primary" value="Upload"/>
        </p>
    </form>
{% endblock %}